export const LINK_CONTACT_TO_CLIENT_REQUEST = 'LINK_CONTACT_TO_CLIENT_REQUEST';
export const LINK_CONTACT_TO_CLIENT_SUCCESS = 'LINK_CONTACT_TO_CLIENT_SUCCESS';
export const LINK_CONTACT_TO_CLIENT_FAILURE = 'LINK_CONTACT_TO_CLIENT_FAILURE';